### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ppepos** [MarcEtienneDery/Botgammon#1]
- [x] API
  - [x] Voir comment ça marche
  - [x] ...
  - [x] Le faire
- [x] L'intelligence Artificielle 
  - [x] Implementer le monde du backgammon
  - [x] Faire un expectiminimax <3
  - [x] Essayer des fonctions d'évalutations
  - [x] Pruning
- [x] Regarder pour un UI possible
- [x] **Faire le rapport**
